package p0002

import (
	"github.com/flily/projeuler.go/framework"
)

const LIMIT = 4_000_000

var Problem = framework.InitProblem(2, "Even Fibonacci Numbers").
	WithAnswer(4613732).
	Solution("naive", SolveNaive).
	Solution("naive no branch", SolveNaiveNoBranch).
	WithDescription(
		`Even Fibonacci Numbers`,
		``,
		`Each new term in the Fibonacci sequence is generated by adding the previous two`,
		`terms. By starting with 1 and 2,, the first 10 terms will be:`,
		``,
		`1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...`,
		``,
		`By considering the terms in the Fibonacci sequence whose values do not exceed`,
		`four million, find the sum of the even-valued terms.`,
	)
