name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3

  coverage:
    name: Go Coverage
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Unit test
      run: go test -v ./...

    - name: Run on all solutions
      run: |
        go build ./cmd/projeuler
        ./projeuler -check -method-timeout=1s
